id: IB1ABBCEE
legacy_id: P010702
ocr_import_info:
  bdrc_scan_id: W2PD19431
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T13:12:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T10:36:21.048108+00:00'
last_modified: 2022-09-03 18:38:18.075028
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD19431
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2PD19431
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་ཆེན་སྔ་འགྱུར་དགེ་མང་དགོན་གྱི་སྒྲུབ་སྐོར་ཕྱོགས་བསྒྲིགས་གྲུབ་གཉིས་འདོད་དགུའི་བང་མཛོད།
statistics:
  ocr_word_mean_confidence_index: 0.7169746636163394
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I4PD4315:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4315
      total_pages: 538
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4PD4315.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6520566096170967
    legacy_id: v004
  I4PD4313:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4313
      total_pages: 800
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD4313.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6258895626614128
    legacy_id: v002
  I4PD4316:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4316
      total_pages: 716
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4PD4316.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6700608279081084
    legacy_id: v005
  I4PD4314:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4314
      total_pages: 566
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4PD4314.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5741587090482753
    legacy_id: v003
  I4PD4317:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4317
      total_pages: 804
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4PD4317.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6177006050059373
    legacy_id: v006
  I4PD4320:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4320
      total_pages: 362
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I4PD4320.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8701707912273714
    legacy_id: v009
  I4PD4319:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4319
      total_pages: 394
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4PD4319.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8718170973792196
    legacy_id: v008
  I4PD4312:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4312
      total_pages: 370
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD4312.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8856987615200708
    legacy_id: v001
  I4PD4318:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4318
      total_pages: 970
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4PD4318.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5869545617793872
    legacy_id: v007
  I4PD4321:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4321
      total_pages: 756
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I4PD4321.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8843372996988594
    legacy_id: v010
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
