id: IB1ABBCEE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T13:17:02+00:00'
last_modified: '2022-06-08T16:55:01.697875+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19431
  title: 'གསང་ཆེན་སྔ་འགྱུར་དགེ་མང་དགོན་གྱི་སྒྲུབ་སྐོར་ཕྱོགས་བསྒྲིགས་གྲུབ་གཉིས་འདོད་དགུའི་བང་མཛོད། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    919F:
      image_group_id: I4PD4312
      title: ''
      total_pages: 370
      order: 1
      base_file: 919F.txt
    '5306':
      image_group_id: I4PD4313
      title: ''
      total_pages: 800
      order: 2
      base_file: 5306.txt
    '2968':
      image_group_id: I4PD4314
      title: ''
      total_pages: 566
      order: 3
      base_file: 2968.txt
    0C4A:
      image_group_id: I4PD4315
      title: ''
      total_pages: 538
      order: 4
      base_file: 0C4A.txt
    '4750':
      image_group_id: I4PD4316
      title: ''
      total_pages: 716
      order: 5
      base_file: 4750.txt
    24BB:
      image_group_id: I4PD4317
      title: ''
      total_pages: 804
      order: 6
      base_file: 24BB.txt
    940C:
      image_group_id: I4PD4318
      title: ''
      total_pages: 970
      order: 7
      base_file: 940C.txt
    A251:
      image_group_id: I4PD4319
      title: ''
      total_pages: 394
      order: 8
      base_file: A251.txt
    963B:
      image_group_id: I4PD4320
      title: ''
      total_pages: 362
      order: 9
      base_file: 963B.txt
    141F:
      image_group_id: I4PD4321
      title: ''
      total_pages: 756
      order: 10
      base_file: 141F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
