id: opecha:P010702
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19431
  title: 'གསང་ཆེན་སྔ་འགྱུར་དགེ་མང་དགོན་གྱི་སྒྲུབ་སྐོར་ཕྱོགས་བསྒྲིགས་གྲུབ་གཉིས་འདོད་དགུའི་བང་མཛོད། '
  volume: ''
  author: ''
